# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.BigIntegerField(default=0, verbose_name='Start timestamp')),
                ('end_timestamp', models.BigIntegerField(default=0, verbose_name='End timestamp')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Actived room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Room name')),
                ('description', models.CharField(max_length=1000, verbose_name='Room description')),
                ('image_url', models.URLField(max_length=1000, verbose_name='Room imageURL')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='system.Room'),
        ),
    ]
