# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Activated room'),
        ),
    ]
